sonar.projectKey=catdog-joserodolfo_catdog-aula
sonar.projectName=catdog-aula
sonar.projectVersion=0.0.1
sonar.organization=catdog-joserodolfo
sonar.token=${SONAR_TOKEN}
sonar.sources=services/backend/src,services/frontend/src
sonar.tests=services/backend/src,services/frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=services/backend/coverage/lcov.info,services/frontend/coverage/lcov.info